### ISSUE TITLE
jd_CityNew助力码分割错误

### ISSUE THREAD

**Issue by 1910054472** [wuzhi05/MyActions#10]
[![5swMPs.png](https://z3.ax1x.com/2021/10/21/5swMPs.png)](https://imgtu.com/i/5swMPs)

******开始【京东账号2】jd_58849040f3ddf*********

开始
"Response code 429 (Too Many Requests)"
城城领现金 API请求失败，请检查网路重试
第2个京东账号将要助力的好友["T","o"," ","M","a","n","y","R","e","q","u","s","t","RtGKzOXyQwinfoWeH4Vh1jRr****************************

【京东账号2（jd_58849040f3ddf）的城城领现金好友互助码】RtGKzeSsRQOjeoPMFIBng********************

2
领红包结果{"code":0,"data":{"bizCode":0,"bizMsg":"success","result":{"currentTimeCash":"0.51","finallyFlag":false,"reachCashLimit":false,"totalCash":"7.66","withdrawBarNum":76},"success":true},"msg":"调用成功"}
获得 0.51 元，共计 7.66 元

开始助力 【T】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【o】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【 】

开始助力 【M】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【a】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【n】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【y】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【R】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【e】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【q】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【u】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【s】

city_getHomeData失败:{"code":-10001,"msg":"请求参数错误"}

开始助力 【t】

**Comment by wuzhi05** [comment]
更新了一下，应该解决了，获取不到助力码导致的，问题不大
